CONFIG_ZMK_STUDIO=y

# Mengaktifkan deep sleep (mati otomatis setelah 15 menit idle)
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Meningkatkan daya pancar Bluetooth agar tidak intermiten antar sisi
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
